security:
  jwt:
    secret-key: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-time: ${JWT_EXPIRATION_TIME:86400000}

spring:
  application.name: hrms

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${calc.email.configuration.host}
    port: ${calc.email.configuration.port}
    username: ${calc.email.configuration.username}
    password: ${calc.email.configuration.password}
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enabled: true
            required: true
    varify:
      host: ${hr.email.url}

  datasource:
    url: jdbc:mysql://${MYSQL_DB_HOST:127.0.0.1}:${MYSQL_DB_PORT:3306}/${MYSQL_DB_NAME:loan-calculator}
    name: {MYSQL_DB_NAME:loan-calculator}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

calc:
  resetPasswordUrl: "http://localhost:4200/accept-invite"
  resetUsername: "http://localhost:4200/accept-invite"
  email:
    configuration:
      host: ${APP_EMAIL_HOST:smtp.gmail.com}
      port: ${APP_EMAIL_PORT:587}
      username: ${APP_EMAIL_USERNAME:lallybaraza1962@gmail.com}
      password: ${APP_EMAIL_PASSWORD:awmv gpdz ptqx ploz}
      verify_email_host: ${APP_VERIFY_EMAIL_HOST:http://localhost:8080}